spring:
  neo4j:
    uri: neo4j+s://32f0743e.databases.neo4j.io
logging:
  level:
    org:
      springframework:
        data:
          neo4j: DEBUG
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /
  endpoint:
    health:
      show-details: always