server:
  error:
    include-message: always
logging:
  level:
    org:
      springframework:
        data:
          neo4j: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always