spring:
  neo4j:
    uri: bolt://localhost:7687
logging:
  level:
    org:
      springframework:
        data:
          neo4j: DEBUG
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /
  endpoint:
    health:
      show-details: always